### ISSUE TITLE
Kész van

### ISSUE THREAD

**Issue by Moldovan-Milan** [Teaching-projects/januari-beadando-Moldovan-Milan#1]
Szép napot Tanár Úr!
Kész van a beadandóm.

**Comment by hegyhati** [comment]
Szep, exception-t hol tanultad?

Egy aprosagot talaltam: a `hossz`-od szerintem `str` es utana ezt igy is adod at a `range`-nek, az nem az igazi. 

Ezt meg kalapald ki rajta, aztan irj, en meg irom be kretaba az otost.

**Comment by Moldovan-Milan** [comment]
Szép napot!

Kijavítottam.

Van  youtube-on  egy csatorna, a neve Kóder Klub. Nyáron nézegettem a videóit. Ott tanultam az exception-t.

**Comment by Moldovan-Milan** [comment]
> Szep, exception-t hol tanultad?
> 
> Egy aprosagot talaltam: a `hossz`-od szerintem `str` es utana ezt igy is adod at a `range`-nek, az nem az igazi.
> 
> Ezt meg kalapald ki rajta, aztan irj, en meg irom be kretaba az otost.

**Comment by hegyhati** [comment]
No, ez nem igy. Szoval a parancs inputjanalnal levetted az int-re konvertalast, de nem ertem, miert, hiszen utana egeszkent csinalsz osszehasonlitas. A hossz-nal meg az lett  volna a lenyeg, hogy a fuggveny mar eleve int-et kapjon. Tehat a meghivas elott legyen int-re konvertalva.

Igy vilagos, mire gondolok?

**Comment by Moldovan-Milan** [comment]
Igen, most már értem. Kijavítottam és fel is töltöttem.

**Comment by hegyhati** [comment]
Szuper, otos.
